//  Vetor de títulos das notícias
var vetTitulo = [
  "Homem paraplégico volta a andar após receber implantes no cérebro em técnica pioneira",
  "Três áreas em que a inteligência artificial já está melhorando nossas vidas",
  "O único restaurante do mundo que serve carne cultivada em laboratório",
  "Por que ainda não é possível fazer um transplante de cérebro",
  "A radical influência da tecnologia no sono das pessoas",
  "Meninas no limite' por que as adolescentes sofrem mais com problemas causados por redes sociais"
];

// Vetor de autores das notícias
var vetAutor = [
  "Pallab Ghosh",
  "Jean Tyler",
  "Nick Marsh",
  "Jannette Rodríguez Pallares",
  "Catherine Coveney e Eric L. Hsu",
  "Ángel Bermúdez"
];

// Vetor de textos das notícias
var vetTexto = [
  "Um homem paraplégico conseguiu andar simplesmente pensando nisso graças a implantes cerebrais eletrônicos, uma tecnologia da medicina que, segundo ele, mudou sua vida. Gert-Jan Oskam, um holandês de 40 anos, perdeu o movimento das pernas em um acidente de bicicleta há 12 anos. Os implantes eletrônicos transmitem sem fio seus pensamentos para suas pernas e pés por meio de um segundo implante em sua coluna. O sistema ainda está em estágio experimental, mas foi considerado muito promissor. Ele também pode agora ficar em pé e subir escadas. Foi uma longa jornada, mas agora posso me levantar e tomar uma cerveja com meu amigo. É um prazer de que muitas pessoas não têm ideia. A tecnologia, publicada na revista científica Nature, foi desenvolvida por pesquisadores suíços. A neurocirurgiã Jocelyn Bloch, professora da Universidade de Lausanne(Suíça) que realizou a delicada cirurgia de inserção dos implantes, destaca que o sistema continua em estágio de pesquisa básica e faltam muitos anos para estar disponível para pacientes com paralisia. Ela diz à BBC News, no entanto, que o objetivo da equipe era tirá - lo do laboratório e colocá - lo em operação o mais rápido possível. O importante para nós não é apenas realizar um experimento científico, mas eventualmente dar mais acesso a mais pessoas com lesões na medula espinhal que estão acostumadas a ouvir dos médicos que precisam se acostumar com o fato de que nunca mais terão movimentos. Harvey Sihota é executivo-chefe da ONG britânica Spinal Research, que não participou da pesquisa. Segundo ele, embora haja um longo caminho a percorrer antes que a tecnologia esteja disponível, ela é muito promissora. Embora ainda haja muito a melhorar com essas tecnologias, este é outro passo promissor no campo da neurotecnologia e seu papel na restauração da função e independência de nossa comunidade de lesões na medula espinhal.",

  "O que a inteligência artificial gera de fascínio, gera também de medo. Para Daniela Rus, que trabalha com essa tecnologia, o veredito depende de nós, humanos. É uma ferramenta que não é inerentemente boa ou ruim, é o que se decide fazer com ela. Como qualquer outra — como uma faca, o fogo —, ela pode ser usada de diferentes maneiras, e precisamos garantir que seja usada por razões positivas, diz Rus, professora de engenharia elétrica e ciência da computação no Instituto de Tecnologia de Massachusetts (MIT), nos Estados Unidos, além de diretora do Laboratório de Ciência da Computação e Inteligência Artificial (CSAIL). Quanto mais pessoas participam da inteligência artificial, mais ela se democratiza, mais pode florescer. Rus reconhece que a comunidade que pesquisa a inteligência artificial não entende todos os aspectos da tecnologia, mas está trabalhando muito para obter uma compreensão mais profunda e aprender sobre seus possíveis usos e obstáculos. E afirma que há muitos que se dedicam ao desenvolvimento de ferramentas contra a desinformação e contra outras coisas que podem dar errado com a inteligência artificial. Rus se sente otimista. (A inteligência artificial) pode nos capacitar de várias maneiras: pode melhorar nossa memória, velocidade de cálculo, capacidade de previsão, pode nos ajudar a julgar situações para tomarmos melhores decisões. A seguir, Daniela Rus e outra entusiasta da tecnologia, a engenheira Mihaela van der Schaar, apontam como a inteligência artificial já está afetando nossas vidas positivamente — da saúde ao transporte. Há muito debate sobre como a inteligência artificial (IA) pode substituir os humanos, mas estou muito interessada em construir uma IA que não substitua os humanos, mas que possa nos tornar, independentemente da idade, mais inteligentes. Uma IA para o empoderamento humano, aponta Mihaela van der Schaar, professora de inteligência artificial e medicina da Universidade de Cambridge, na Inglaterra.",

  "Parece frango, tem cheiro de frango e gosto de frango. Eu jamais imaginaria que o pedaço de carne que está na minha frente não veio de uma fazenda. Mas ele foi feito em um laboratório, em uma propriedade industrial, a alguns quilômetros de distância. Estou no Huber's Butchery and Bistro, em Singapura, o único restaurante do mundo a oferecer o que se chama de carne de cultura no cardápio. A resposta dos clientes tem sido fenomenal, de acordo com o proprietário do restaurante. A criadora da carne, a empresa californiana Eat Just, garante que seu produto consegue ser ético, limpo e ecológico, sem abrir mão do sabor. Bilhões de dólares estão sendo investidos nesse setor, mas há grandes dúvidas sobre sua viabilidade a longo prazo. Desde que o primeiro hambúrguer produzido em laboratório foi apresentado em Londres, em 2013, uma criação que custou impressionantes US$ 330 mil (R$ 1,8 milhão), dezenas de empresas em todo o mundo se juntaram à corrida para comercializar carne cultivada em laboratório a preços razoáveis. Até agora, apenas a Eat Just conseguiu que seu produto fosse aprovado para venda ao público depois que os reguladores de Singapura, o único país do mundo que permite a venda desse tipo de carne, deram luz verde ao seu frango em dezembro de 2020. Mas o produto está longe de ser produzido em larga escala. Nuggets de frango cultivados em laboratório estiveram brevemente no menu de um clube privado em 2021. Essa parceria durou alguns meses e, neste ano, o Huber's começou a oferecer ao público em geral um sanduíche de frango e um prato de macarrão com frango, embora apenas uma vez por semana.",

  "Gostaria de convidar você a fazer uma viagem ao passado. Vamos voltar até 1970. Em março daquele ano, o renomado neurocirurgião americano Robert J. White (1926-2010) realizou uma operação insólita. Em um hospital de Cleveland, nos Estados Unidos, White conseguiu, pela primeira vez, conectar a cabeça de um macaco ao corpo de outro. A intervenção levou 18 horas. Quando o macaco acordou, ele conseguia ver, ouvir, cheirar e até morder. A notícia trouxe entusiasmo. Podemos dizer que aquele foi o primeiro transplante de cérebro - ou, melhor dizendo, de cabeça - realizado com sucesso. White era profundamente religioso e não foi assessor de bioética médica de dois papas por acaso. Por isso, ele preferiu chamar a intervenção de transplante de corpo. Ele tinha certeza de que o cérebro continha a alma e de que ela poderia ser transferida para o novo receptor. Mas o sucesso durou pouco. O macaco morreu depois de alguns dias. White prosseguiu com seu trabalho, realizando centenas de outros experimentos. E, até o fim dos seus dias, fantasiou com a repetição da sua façanha em seres humanos. Ele chegou até a ter um candidato - um jovem tetraplégico que desejava conseguir um corpo melhor. Mas o seu sonho nunca chegou a ser realizado.  White não foi o único a tentar realizar o transplante de cérebro humano, mas certamente foi o mais conhecido. É dele o mérito de ter desenvolvido diversos procedimentos cirúrgicos que continuam sendo utilizados até hoje para salvar vidas. Mas seu trabalho também foi objeto de duras críticas. White chegou a ser considerado o símbolo da indústria bruta e cruel da vivissecção, o que pode ter frustrado suas aspirações ao prêmio Nobel.",

  "Dos monitores de sono até os medicamentos para ficar acordado, o século 21 vem trazendo um conjunto de novas tecnologias capaz de alterar radicalmente a forma como dormimos. Muitas dessas novas tecnologias pretendem otimizar o sono. Elas prometem ajudar a adaptar o cronograma do sono à nossa vida social, ajudar-nos a dormir por mais tempo ou até pular uma noite de sono por completo. Analisamos aqui como a tecnologia vem permeando o nosso sono e o que nos reserva o futuro. As pílulas para dormir receberam recentemente a companhia de uma série de medicamentos para ficar acordado, que são alternativas supostamente mais seguras e potentes do que a cafeína. Aparentemente, elas funcionam melhor com pessoas que já dormem pouco e não têm grande efeito sobre as pessoas que já estão bem descansadas. O modafinil é conhecido por efeitos de aumento da cognição (especialmente em pessoas com falta de sono) e, supostamente, pode manter as pessoas acordadas e alertas por vários dias seguidos. Alguns estudos científicos demonstram que, realmente, pode ser verdade, mas os resultados são contraditórios. Outras pesquisas demonstram efeitos similares à cafeína. A droga foi desenvolvida para ajudar pessoas com narcolepsia, mas começou a ser usada por seus efeitos de aumento da concentração. A venda de modafinil é controlada na maioria dos países (permitida apenas com receita médica). As pessoas que usam a droga para aumentar a cognição ou para ficar acordado compram o remédio no mercado clandestino ou com amigos que conseguiram a receita. O modafinil é popular entre estudantes. Em 2020, pesquisadores da Universidade de Loughborough, na Inglaterra, concluíram que, dos 506 estudantes pesquisados em 54 universidades britânicas, 19% haviam tomado substâncias para aumentar a cognição.",

  "Alguns dizem que é uma emergência de saúde pública — e os números certamente indicam que algo está acontecendo. As adolescentes nos Estados Unidos estão experimentando níveis sem precedentes de tristeza eansiedade. Um estudo do Centro de Controle de Doenças dos EUA (CDC), com dados de 2021, indica que quase três em cada cinco meninas adolescentes relataram sentir-se constantemente tristes ou sem esperança, o que representa um aumento de quase 60% em relação a 2011, quando 36% das mulheres jovens disseram que se sentiam assim. No caso dos meninos também houve piora, mas bem menor, já que o número dos que relataram esses sentimentos negativos passou de 21% para 29% no mesmo período. Outro indicador preocupante do estudo é o aumento do número de adolescentes que consideraram seriamente o suicídio: uma em cada três, o que representa um aumento de quase 60% em relação a 2011 e o dobro do número de meninos (14%). Embora as autoridades de saúde apontem que o alto risco de suicídio, depressão, uso de drogas e outros problemas em adolescentes pode responder a uma mistura de vários fatores, os especialistas destacam o papel das redes sociais na deterioração da saúde mental dos jovens. Entre esses especialistas está Donna Jackson Nakazawa, escritora especializada em neurociência, imunologia e emoção, que, no final de 2022, publicou o livro Girls on the Brink (Garotas no Limite, em tradução livre; sem edição brasileira), no qual explora essa situação. Nesta conversa com a BBC Mundo, o serviço em espanhol da BBC, a autora explica as causas biológicas, sociais e culturais por trás do aumento chocante do número de adolescentes com problemas de depressão e ansiedade nos Estados Unidos. Embora reconheça que isso é causado por múltiplos fatores, ela afirma que as redes sociais são as principais culpadas e são muito mais tóxicas para as meninas."
];

// Vetor de imagens das notícias
var vetImagens = [
  "imgHomemParaplegico.png",
  "imgAreasInteligenciaArtificial.png",
  "imgUnicoRestauranteDoMundo.png",
  "imgTransplanteCerebro.png",
  "imgRadicalInfluenciaTecnologia.png",
  "imgMeninasNoLimite.png"
];